name: device_repository
description: Dart package which takes device data.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  build_runner: ^2.4.7