name: post_repository
description: Dart package which manages the posts domain.
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  uuid: ^3.0.0
  
dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.5.2
  json_serializable: ^6.7.1